version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  #install:
    #commands:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - pwd
      - echo 'hello Ben'
      - ls -al
      - pip install -r $CODEBUILD_SRC_DIR/pdftotext/requirements.txt
      - python $CODEBUILD_SRC_DIR/pdftotext/process.py
      # - command
  #post_build:
    #commands:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths